# =========================
# Server
# =========================
server.port=${PORT:8080}

# =========================
# PostgreSQL (Neon)
# =========================
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# JWT
# =========================
application.security.jwt.secret-key=ZmlsZS1jYXJlZXJvcy1zZWN1cml0eS1rZXkta2V5LWZvci1hdXRoZW50aWNhdGlvbi1wdXJwb3Nlc29ubHk=
application.security.jwt.expiration=86400000

# =========================
# File Upload
# =========================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
application.resume.upload-dir=uploads